version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=foo
      - MYSQL_PASSWORD=foo
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
        - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always

  borg:
    image: borgbackup
    volumes_from:
        - db:ro
        - app:ro
    volumes:
        - /home/ubuntu/backup:/backup
    restart: always

    environment:
        - BORG_REPO=/backup/borgrepo